### ISSUE TITLE
issue while getting data from flc.fits

### ISSUE THREAD

**Issue by srinadh99** [profjsb/deepCR#11]
While getting data from flc.fits, it's showing "TypeError: buffer is too small for requested array" as follows. PLease provide me solution.

TypeError                                 Traceback (most recent call last)
<ipython-input-37-faa4d77b96fc> in <module>
      1 #image = fits.getdata("jdba2sooq_flc.fits")
----> 2 image = fits.getdata("jdba2sooq_flc.fits")[:512,:512]
      3 
      4 #image = fits.getdata("jdba2sooq_flc.fits")
      5 

~/.local/lib/python3.5/site-packages/astropy/io/fits/convenience.py in getdata(filename, header, lower, upper, view, *args, **kwargs)
    194             try:
    195                 hdu = hdulist[1]
--> 196                 data = hdu.data
    197             except IndexError:
    198                 raise IndexError('No data in this HDU.')

~/.local/lib/python3.5/site-packages/astropy/utils/decorators.py in __get__(self, obj, owner)
    742                 return val
    743             else:
--> 744                 val = self.fget(obj)
    745                 obj.__dict__[self._key] = val
    746                 return val

~/.local/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py in data(self)
    228             return
    229 
--> 230         data = self._get_scaled_image_data(self._data_offset, self.shape)
    231         self._update_header_scale_info(data.dtype)
    232 

~/.local/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py in _get_scaled_image_data(self, offset, shape)
    694         code = BITPIX2DTYPE[self._orig_bitpix]
    695 
--> 696         raw_data = self._get_raw_data(shape, code, offset)
    697         raw_data.dtype = raw_data.dtype.newbyteorder('>')
    698 

~/.local/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py in _get_raw_data(self, shape, code, offset)
    506                               offset=offset)
    507         elif self._file:
--> 508             return self._file.readarray(offset=offset, dtype=code, shape=shape)
    509         else:
    510             return None

~/.local/lib/python3.5/site-packages/astropy/io/fits/file.py in readarray(self, size, offset, dtype, shape)
    332 
    333                 return np.ndarray(shape=shape, dtype=dtype, offset=offset,
--> 334                                   buffer=self._mmap)
    335             else:
    336                 count = reduce(operator.mul, shape)

TypeError: buffer is too small for requested array

**Comment by kmzzhang** [comment]
This would be an issue on the astropy side. Updating to python>=3.6 and astropy>=3.2.1 should fix it.
